import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/component/Footer";
import Megamenu from "@/component/Megamenu";
import ClientLayoutWrapper from "@/component/ClientLayoutWrapper";
import { SpeedInsights } from "@vercel/speed-insights/next"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BullsEye",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Megamenu />
        <ClientLayoutWrapper>
          {children}
            <SpeedInsights />
        </ClientLayoutWrapper>
        <Footer />
       
      </body>
       {/* Screener always visible */}
       

    </html>
  );
}
