// app/layout.js

import "./globals.css";
import Footer from "@/component/Footer";
import Megamenu from "@/component/Megamenu";
import ClientLayoutWrapper from "@/component/ClientLayoutWrapper";
import { SpeedInsights } from "@vercel/speed-insights/next";



export const metadata = {
  title: "BullsEye",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en" suppressHydrationWarning>
      <head>
       
         <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Loopple/loopple-public-assets@main/motion-tailwind/motion-tailwind.css"/>
      </head>
      <body
        className="bg-black text-black "
      >
        <Megamenu />
        <ClientLayoutWrapper>
          {children}
          <SpeedInsights />
        </ClientLayoutWrapper>
       
         <Footer />
        
      </body>
    </html>
  );
}

